(function(){'use strict';var d;var f=/^(https:\/\/(www\.gstatic\.com\/vr\/ads\/index\.html\?assetId=|poly\.google\.com\/view\/))?([\w-_]+)$/;var m=function(a,b,c,e){for(var k=[],g=3;g<arguments.length;++g)k[g-3]=arguments[g];g=b.split(".");for(var h=a,l=0;h&&l<g.length;l++)h=h[g[l]];g=h&&"function"===typeof h[c]?h[c]:void 0;g&&g.apply(null,k)};var n=function(a){m(window,"gwd.rumUtil","logTimingEvent","gwd3dmodel_"+(a?"start":"stop")+"Timer_TimeToFirstFrame",window);a?Enabler.startTimer("TimeToFirstFrame"):Enabler.stopTimer("TimeToFirstFrame")},p=function(a){a?Enabler.startTimer("TimeToSpritesheet"):Enabler.stopTimer("TimeToSpritesheet")},r=function(a){a?Enabler.startTimer("TotalEngagement"):Enabler.stopTimer("TotalEngagement");q()},t=0,u=0,q=function(){0==t&&(t=performance.now());for(var a=Math.floor((performance.now()-t)/100);u<=a;u++)Enabler.counter("TotalSessionDurationDeciseconds",
!0)},v={Engagement:function(){Enabler.reportEngagement()},Zoom:function(){Enabler.counter("Zoom",!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},SpritesheetRotate:function(){Enabler.counter("SpritesheetRotate",!0)},Hotspot1Click:function(){Enabler.counter("Hotspot1Click",!0)},Hotspot2Click:function(){Enabler.counter("Hotspot2Click",!0)},Hotspot3Click:function(){Enabler.counter("Hotspot3Click",!0)},Hotspot4Click:function(){Enabler.counter("Hotspot4Click",
!0)},Hotspot5Click:function(){Enabler.counter("Hotspot5Click",!0)}},w={};var x=function(a,b,c){if(c){var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,c)}else e=document.createEvent("Event"),e.initEvent(a,!0,!0);b.dispatchEvent(e)},y=function(a,b,c){var e=function(k){a.removeEventListener(b,e);c(k)};a.addEventListener(b,e)};var z=function(){};goog.inherits(z,HTMLElement);d=z.prototype;d.createdCallback=function(){this.a=null;this.h=!1};d.attachedCallback=function(){window.Enabler&&Enabler.isServingInLiveEnvironment()&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));A(this)};
d.detachedCallback=function(){window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));this.f&&(clearTimeout(this.f),this.f=void 0)};d.attributeChangedCallback=function(a){switch(a){case "id-url":case "enable-thumbnail":case "enable-spritesheet":case "enable-quicklook":case "transparent":A(this)}};
d.handleEvent=function(a){switch(a.type){case "click":this.i&&a.target===this.c&&a.stopPropagation();break;case "start-timer":case "stop-timer":var b=a.detail.timer;if("start-timer"===a.type)"TotalEngagement"===b&&(this.i=!0,r(!0),x("interaction-start",this),this.a&&this.a.parentNode&&this.a.parentNode.removeChild(this.a));else if("TotalEngagement"===b)this.i=!1,r(!1),x("interaction-end",this);else if("TimeToFirstFrame"===b||"TimeToSpritesheet"===b)"TimeToFirstFrame"===b?n(!1):p(!1),this.classList.add("ready"),
B(this);break;case "scene-rendered":case "camera-changed":a.stopPropagation();x(a.type,this,a.detail);break;case "hotspot-clicked":b=a.detail.index;v.Engagement();b="Hotspot"+b+"Click";if(v[b])v[b]();a.stopPropagation();x(a.type,this,a.detail);break;case "increment-counter":b=a.detail;a=b.counter;b=b.cumulative?v:w;if(b[a])b[a]();break;case studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH:C(this).removeAttribute("scroll-gating");Enabler.reportEngagement();q();break;case studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH:C(this).setAttribute("scroll-gating",
""),q()}};
var C=function(a){a.c||(a.c=a.ownerDocument.createElement("gltf-viewer"),a.c.setAttribute("scroll-gating",""),a.c.addEventListener("start-timer",a),a.c.addEventListener("stop-timer",a),a.c.addEventListener("increment-counter",a),a.c.addEventListener("scene-rendered",a),a.c.addEventListener("camera-changed",a),a.c.addEventListener("hotspot-clicked",a),a.c.addEventListener("click",a),a.appendChild(a.c));return a.c},D=function(a){var b=a.getAttribute("gesture-cue-icon");if(b){a.a&&a.a.parentNode&&a.a.parentNode.removeChild(a.a);
a.a=a.ownerDocument.createElement("div");a.a.style.background='url("'+b+'") 100% 100% / 100% no-repeat';a.a.classList.add("gesture-cue");b=parseFloat(a.getAttribute("gesture-cue-duration"));isFinite(b)||(b="29");a.a.style.animationIterationCount=0>b?"infinite, 1":(b/2).toFixed(1)+", 1";if(b=a.getAttribute("gesture-cue-text")){var c=a.ownerDocument.createElement("p");c.textContent=b;a.a.appendChild(c)}a.appendChild(a.a)}},E=function(a,b){b=void 0===b?function(){}:b;var c=a.ownerDocument.querySelector('script[src="https://www.gstatic.com/vr/ads/gltfviewer/gltfviewer_min.js"]');
if(c&&c.__status__)b();else{var e=function(k){k.target.__status__=k.type;b()};c?(y(c,"load",e),y(c,"error",e)):(c=a.ownerDocument.createElement("script"),c.setAttribute("src","https://www.gstatic.com/vr/ads/gltfviewer/gltfviewer_min.js"),y(c,"load",e),y(c,"error",e),a.ownerDocument.head.appendChild(c))}},A=function(a){a.f||(a.f=setTimeout(a.gwdLoad.bind(a),0))};
z.prototype.gwdLoad=function(){var a=this;this.f&&(clearTimeout(this.f),this.f=void 0);var b=(this.getAttribute("id-url")||"").trim().match(f);if(b){var c=this.hasAttribute("enable-thumbnail"),e=this.hasAttribute("enable-spritesheet"),k=this.hasAttribute("enable-quicklook"),g=this.hasAttribute("transparent");b="assetId="+b[3];var h=(this.getAttribute("data-settings")||"").trim(),l=c;-1===h.indexOf("//")&&h.match("settings.json")&&(b+="&settingsUrl="+h,l=!1);b=b+("&thumbnail="+l)+("&spritesheet="+
e)+("&quicklook="+k);b+="&bg="+!g;if("localhost"==window.location.hostname||"file:"==window.location.protocol)b+="&cache=false";e=C(this);e.getAttribute("query")!==b&&(E(this),this.h=!1,c&&requestAnimationFrame(function(){"none"!==getComputedStyle(a).backgroundImage&&B(a)}),this.classList.remove("ready"),e.setAttribute("query",b),n(!0),p(!0));D(this)}else B(this)};z.prototype.gwdIsLoaded=function(){return this.h};var B=function(a){E(a,function(){a.h||(a.h=!0,x("ready",a))})};d=z.prototype;
d.setYaw=function(a,b){F(this,{name:"setYaw",yawAngle:a,pauseRestingAnimation:b})};d.setTargetYaw=function(a){F(this,{name:"setTargetYaw",yawAngle:a})};d.setTargetPitch=function(a){F(this,{name:"setTargetPitch",pitchAngle:a})};d.incrementTargetPitch=function(a){F(this,{name:"incrementTargetPitch",pitchAngle:a})};d.setTargetZoom=function(a){F(this,{name:"setTargetZoom",scale:a})};d.incrementTargetZoom=function(a){F(this,{name:"incrementTargetZoom",scale:a})};
d.setTargetPivot=function(a,b,c){F(this,{name:"setTargetPivot",X:a,Y:b,Z:c})};d.setTargetLocalPan=function(a,b,c){F(this,{name:"setTargetLocalPan",X:a,Y:b,Z:c})};d.setMaterialColor=function(a,b,c,e){F(this,{name:"setMaterialColor",material:a,r:b,g:c,b:e})};d.setMaterialClearCoat=function(a,b,c){F(this,{name:"setMaterialClearCoat",material:a,value:b,roughness:c})};d.playAnimation=function(a){F(this,{name:"animationPlay",animationName:a})};
d.pauseAnimation=function(a){F(this,{name:"animationPause",animationName:a})};d.setAnimationTime=function(a,b){F(this,{name:"animationSetTime",animationName:a,time:b})};d.incrementAnimationTime=function(a,b){F(this,{name:"animationIncrementTime",animationName:a,time:b})};d.addHotspot=function(a,b,c,e){F(this,{name:"addHotspot",hotspotName:a,x:b,y:c,z:e})};d.lookAtHotspot=function(a){F(this,{name:"lookAtHotspot",hotspotName:a})};var F=function(a,b){E(a,function(){var c=C(a);c.handleMessage&&c.handleMessage(b)})};
document.registerElement("gwd-3d-model",{prototype:z.prototype});}).call(this);
